<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MS_GameHUD</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.4</Version>
	<GameHUD_Shared_Version>1.0.2</GameHUD_Shared_Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModSharp.GameHUD.Shared" Version="$(GameHUD_Shared_Version)" />
    <PackageReference Include="ModSharp.Sharp.Shared" Version="2.1.88" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="if exist $(SolutionDir)build rmdir /s/q $(SolutionDir)build" />
	  <Exec Command="if not exist $(SolutionDir)build mkdir $(SolutionDir)build" />
	  <Exec Command="if not exist $(SolutionDir)build\modules mkdir $(SolutionDir)build\modules" />
	  <Exec Command="if not exist $(SolutionDir)build\modules\$(TargetName) mkdir $(SolutionDir)build\modules\$(TargetName)" />
	  <Exec Command="copy /Y $(TargetDir)$(TargetName).dll $(SolutionDir)build\modules\$(TargetName)\$(TargetName).dll" />
	  <Exec Command="copy /Y $(TargetDir)$(TargetName).deps.json $(SolutionDir)build\modules\$(TargetName)\$(TargetName).deps.json" />
	  
	  <Exec Command="if not exist $(SolutionDir)build\shared mkdir $(SolutionDir)build\shared" />
	  <Exec Command="if not exist $(SolutionDir)build\shared\MS-GameHUD-Shared mkdir $(SolutionDir)build\shared\MS-GameHUD-Shared" />

	  <ItemGroup>
		  <GameHUD_Shared_Dll Include="$(NuGetPackageRoot)\modsharp.gamehud.shared\$(GameHUD_Shared_Version)\lib\net10.0\**\*.dll" />
	  </ItemGroup>
	  <Copy SourceFiles="@(GameHUD_Shared_Dll)" DestinationFolder="$(TargetDir)" />

	  <Exec Command="copy /Y $(TargetDir)MS-GameHUD-Shared.dll $(SolutionDir)build\shared\MS-GameHUD-Shared\MS-GameHUD-Shared.dll" />
  </Target>

</Project>
