<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MS_GameHUD_Example</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModSharp.GameHUD.Shared" Version="1.0.1" />
    <PackageReference Include="ModSharp.Sharp.Shared" Version="2.1.88" />
  </ItemGroup>

</Project>
